# Welcome to Jekyll!

title: GameHook
tagline: Explore and modify emulated games in real-time via a dashboard and API.
highlighter: rouge
discord_invite_link: https://discord.gg/BXRetNZdkM
github_link: https://github.com/gamehook-io/gamehook

plugins:
- jekyll-remote-theme

remote_theme: gamehook-io/jekyll-theme-gamehook

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"