version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll
    command: jekyll serve --watch --force_polling --drafts --verbose
    ports:
      - 4000:4000
    volumes:
        - .:/srv/jekyll
        - ./vendor/bundle:/usr/local/bundle
